name = "Coconots"
uuid = "2061d889-07fc-48e0-ab41-7cc4d945d6d4"
authors = ["Manuel Huth", "Robert C. Jung", "Andy Tremayne"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
